name: Build

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Base Setup
      uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

    - name: Install dependencies
      run: python -m pip install -U "jupyterlab>=4.0.0,<5"

    - name: Build the extension
      run: |
        set -eux
        python -m pip install .[test]

        jupyter server extension list
        jupyter server extension list 2>&1 | grep -ie "jupyter_exam.*OK"

        jupyter labextension list
        jupyter labextension list 2>&1 | grep -ie "jupyter_exam.*OK"
        python -m jupyterlab.browser_check

    - name: Package the extension
      run: |
        set -eux

        pip install build
        python -m build
        pip uninstall -y "jupyter_exam" jupyterlab
